// The survey stores blinded codes (Method_A, …): the browser is never told which
// baseline it is showing, and neither is Firestore. This puts the real names back
// when a researcher reads the data, so the report and every export name baselines.
//
// methods.json is generated by scripts/build_questions_from_evals.py. It is only
// imported from the results page, which is a lazy chunk, so it is not part of what
// a participant downloads.
import methods from './methods.json'

export const METHOD_NAMES = methods

// Unknown codes pass through unchanged: an old response from a study version with
// a different method set still reads sensibly instead of turning into "undefined".
export function methodName(code) {
  return METHOD_NAMES[code] ?? code
}
