// Everything a researcher is likely to change lives in this file.
// Questions (images + method outputs) come from src/data/samples.json, generated by
// `npm run samples` from the folders in public/images/.

export const study = {
  // Stored with every response so answers from different study versions can be told apart.
  id: 'pantomime-v1',

  title: 'Multi-View Image Analogy Study',
  badge: 'Image Editing Research Study',
  subtitle: 'Help us evaluate AI image editing results. No technical background is needed.',
  estimatedTime: '10–15 minutes',

  // How many outputs each participant must rank per question (1st, 2nd, 3rd …).
  ranksPerQuestion: 3,

  // The reference site keeps a fixed question order and shuffles only the outputs.
  shuffleQuestions: false,
  shuffleOutputs: true,

  // Welcome-page illustration (files in public/welcome/). Replace with a real example.
  welcomeExample: {
    a: 'welcome/img_a.png',
    a_prime: 'welcome/img_a_prime.png',
    b: 'welcome/img_b.png',
    b_prime: 'welcome/img_b_prime.png',
    // The edits in the A → A′ example; B′ is described as having the same ones.
    edits: ['Jumping'],
    // Signed azimuth in degrees: negative orbits to the right, positive to the left.
    cameraAzimuth: -90,
  },

  // The two things a participant has to keep track of, shown as chips above the example.
  legend: {
    edits: {
      title: 'Edits',
      help: 'What changed about the subject itself: expression, clothing, pose, or objects added and removed. The output has to show these same edits.',
    },
    camera: {
      title: 'Camera',
      help: 'Where the camera moved to as it orbits the subject. The output has to be seen from that same new viewpoint.',
    },
  },

  // Text shown to participants on each question.
  question: {
    referenceHeading: 'Reference Images — What changes did the AI learn?',
    rankHeading: 'Rank the best outputs',
    rankHelp:
      'Several AI methods produced the results below. Use the rank buttons under each image. The best result gets',
    goodOutput:
      'A good output applies the same edits as A → A′, moves the camera the same way around the subject, keeps the identity and appearance of B, and still looks realistic.',
  },
}

export const RANK_LABELS = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th'].slice(0, study.ranksPerQuestion)
