// Everything a researcher is likely to change lives in this file.
// Questions (images + method outputs) come from src/data/samples.json, generated by
// `npm run samples` from the folders in public/images/.

export const study = {
  // Stored with every response so answers from different study versions can be told apart.
  id: 'pantomime-v1',

  title: 'Multi-View Image Analogy Study',
  badge: 'Image Editing Research Study',
  subtitle: 'Help us evaluate AI image editing results. No technical background is needed.',
  estimatedTime: '10–15 minutes',

  // How many outputs each participant must rank per question (1st, 2nd, 3rd …).
  ranksPerQuestion: 3,

  // The reference site keeps a fixed question order and shuffles only the outputs.
  shuffleQuestions: false,
  shuffleOutputs: true,

  // The reference site defines a consent step but never shows it. Set enabled: false to skip it.
  consent: {
    enabled: true,
    title: 'Before you begin',
    paragraphs: [
      'This study is part of academic research on AI image editing. You will be shown images and asked to rank AI-generated results.',
      'Participation is voluntary and anonymous. We do not collect your name, email or IP address, only your rankings, the time spent on each question and your browser type.',
      'You may stop at any time by closing the page. Answers are only submitted when you reach the end.',
    ],
    checkbox: 'I am 18 or older and agree to take part in this study.',
  },

  // Welcome-page illustration (files in public/welcome/). Replace with a real example.
  welcomeExample: {
    a: 'welcome/img_a.png',
    a_prime: 'welcome/img_a_prime.png',
    b: 'welcome/img_b.png',
    b_prime: 'welcome/img_b_prime.png',
    change: 'Camera orbits 40° to the right',
  },

  // Text shown to participants on each question.
  question: {
    referenceHeading: 'Reference images: what change should be copied?',
    rankHeading: 'Rank the best outputs',
    rankHelp:
      'Several AI methods produced the results below. Use the rank buttons under each image. The best result gets',
    goodOutput:
      'A good output shows the same change as A → A′, keeps the identity and appearance of B, and looks realistic.',
  },
}

export const RANK_LABELS = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th'].slice(0, study.ranksPerQuestion)
